### PR TITLE
Add sources for the file manager program

### PR DESCRIPTION
**Pull request by mmoskal**

### CODE REVIEW

**Comment by THEb0nny** [comment]
@mmoskal What does it do?

**Comment by mmoskal** [comment]
it lets you delete multiple files from the brick

**Comment by THEb0nny** [comment]
> it lets you delete multiple files from the brick

and with what tool. I do not understand. Windows system does not allow deleting. Is there any other file manager?

**Comment by mmoskal** [comment]
you run the program on the brick, and delete files directly using the buttons on the brick

**Comment by THEb0nny** [comment]
@mmoskal What kind of program is that? Should I download it to ev3? The standard manager in ev3 does not allow deleting in the brick save program.

**Comment by mmoskal** [comment]
see here for compiled version and instructions https://pxt.azureedge.net/blob/eff7bd11f4f43bac083d0b43fa051507d7234414//file-manager.pdf

**Comment by mmoskal** [comment]
and here https://makecode.mindstorms.com/fll#why-can-t-i-delete-my-program-uf2-files-from-the-brick-

**Comment by THEb0nny** [comment]
> see here for compiled version and instructions https://pxt.azureedge.net/blob/eff7bd11f4f43bac083d0b43fa051507d7234414//file-manager.pdf[](https://docs.google.com/viewer?url=https%3A%2F%2Fpxt.azureedge.net%2Fblob%2Feff7bd11f4f43bac083d0b43fa051507d7234414%2F%2Ffile-manager.pdf&embedded=true&chrome=false&dov=1)

This is a very cool thing! Thanks! It is not clear only why the documentation does not have this.

**Pull request merged**
