### PR TITLE
RGB raw color sensor simulator support

### PR DESCRIPTION
**Pull request by THEb0nny**
Added simulator support for RGB raw color sensor mode. To do this, I had to change the input code from the sensors and the color sensor code. Prior to this, there was no support for the fact that you can get an array of values.

### CODE REVIEW

**Comment by THEb0nny** [comment]
@jwunderl please see changes...

**Comment by THEb0nny** [comment]
I made the maximum value 512, because. I have never seen more than 300 in my life, so that some of the components gave out ...

**Comment by THEb0nny** [comment]
Prior to this, the color mode was not taken into account. It turns out that the initial value is 50. There is no such index in the array. showPorts didn't output anything for this sensor initially until you chose some color yourself in the simulator. If you look at what the value is there, then 50 is displayed. Therefore, I made the default value 0 - nothing.

**Comment by THEb0nny** [comment]
@jwunderl please see changes

**Review by jwunderl — APPROVED** [review]

**Comment by jwunderl** [comment]
Changes look good to me, tagged in peli for a look if you have time as you have more context on lego but if not I'll try and merge tomorrow / bump beta~

**Pull request merged**
