### PR TITLE
Troubleshooting updates v1.4.25

### PR DESCRIPTION
**Pull request by THEb0nny**
I collected all my solutions to the problems of updating version 1.4.25, which was implemented by riknoll with a pxt update.
https://github.com/microsoft/pxt-ev3/pull/1001

Updated from es6 to es2017 which fixes problems with the simulator and blocks.

Returned the motors field to select medium, large, one or two motors.

Solved the problem with the window that opens when downloading. The window did not open, but the download of the file itself went on, although a message appeared that the download failed. This has been resolved, the buttons have been redesigned in the window.

### CODE REVIEW

**Comment by THEb0nny** [comment]
Problems with the simulator have been resolved.
Before that, it just loaded endlessly.
image

**Comment by THEb0nny** [comment]
Block issues have been resolved. In some categories, like sensors, nothing was displayed.

image

**Comment by THEb0nny** [comment]
Fields for blocks of motors returned. Now there are no problems, but in a different form.

It was not possible to return the previous version, there are too many errors. There are no methods that were previously in the updated version of pxt.

I would like to make the text in the drop-down list in two lines, but so far I have not been able to implement it. The field motor code is based on the field gesture code for microbit. I think this is the best option. I did not find an example where they would implement two from one field in the same way. Now all selections are in one field.
I will update the picture with the port later, I plan to draw, in addition to the port and the letter, an additional drawing of the motor.

I also plan to add support for two medium motors later, but in a separate branch. Therefore, I had to change the names of the blocks that control the two motors to make it clear that the pair of motors B + C (example) are now two large motors.

```
//% whenUsed fixedInstance block="large motors B+C" jres=icons.portBC
//% whenUsed fixedInstance block="large motors A+D" jres=icons.portAD
//% whenUsed fixedInstance block="large motors A+B" jres=icons.portAB
//% whenUsed fixedInstance block="large motors C+D" jres=icons.portCD
```

image

image

image

image

image

image

**Comment by THEb0nny** [comment]
Ev3 download window not launching. This causes a download error.
image

Error: Cannot read properties of undefined (reading 'approveButton').
Buttons with the button approve classes are located in this window.

(This is a window. The screenshot was taken in the stable version.)
image

Problem solved. The code in the showUploadDialogAsync method of the dialogs.tsx file has been changed to return confirmAsync for buttons.
image

**Comment by THEb0nny** [comment]
There remains a problem that I noticed is the field for music files. The selection window appears in the wrong place. Until I solved it. I think that this is a minor problem that does not affect the experience with blocks.

image

**Comment by THEb0nny** [comment]
Instead of the slowmo mode, which was before, a debugger was added, in which slowmo is present.

**Comment by THEb0nny** [comment]
The high const function does not work. Didn't solve the problem.

**Comment by THEb0nny** [comment]
It turned out to update the fieldmusic menu. The menu is now displayed in the correct position. Only I didn’t make an arrow at the menu, I don’t know ...

image

(I mean this arrow.)
image

Next in line is the brickbuttons field...

**Comment by THEb0nny** [comment]
Fixed issue with button select menu position from ev3 brick.

image

**Comment by THEb0nny** [comment]
Repartition of Label for fieldmotos, now it's more readable, it's better.

image

**Comment by THEb0nny** [comment]
Created new icons for motors for dropdown image.

image

image

**Comment by THEb0nny** [comment]
Please see changes @pelikhan @riknoll @abchatra @abchatra @mmoskal

**Review by jwunderl — APPROVED** [review]
Changes all look good to me. I produced a test build if anyone wants to give it a quick go https://makecode.mindstorms.com/app/2e2ed2c12c4b41ac17c9d8d1aacba7d118824b94-3b73a66045

One thing to confirm, it appears that all the new files in `libs/core/jres/icons` are compositions of the existing files in there, correct? that is, you took the files and combined them together yourself from within this repo, they were not taken from elsewhere on the internet?

**Comment by THEb0nny** [comment]
> Changes all look good to me. I produced a test build if anyone wants to give it a quick go https://makecode.mindstorms.com/app/2e2ed2c12c4b41ac17c9d8d1aacba7d118824b94-3b73a66045
> 
> One thing to confirm, it appears that all the new files in `libs/core/jres/icons` are compositions of the existing files in there, correct? that is, you took the files and combined them together yourself from within this repo, they were not taken from elsewhere on the internet?

I created these images based on vector images from the simulator in Adobe Illustrator. I just wanted to use the best quality when creating. I saved it as png, and then I passed these pictures through the base64-image.de service and added the code to icons.jres.

**Comment by jwunderl** [comment]
Sounds good, just wanted to double check there wouldn't be any concerns with licenses on the images if they came from elsewhere. Thank you for the PR, I'll merge and bump it into beta!

**Comment by THEb0nny** [comment]
> Sounds good, just wanted to double check there wouldn't be any concerns with licenses on the images if they came from elsewhere - so since they're coming from our own sim we're good! Thank you for the PR, I'll merge and bump it into beta!

Thanks for the support, I'll wait for the build in beta. I will test on iron in the near future.

**Comment by jwunderl** [comment]
@THEb0nny Hey, finally got a build up, had to go through and fix some pipeline issues / pull in a few build updates in the pxt branch. If you can confirm https://makecode.mindstorms.com/v1.4.29 works as expect I'll update beta with it -- it's currently pinned to an older version for some reason so I figured it'd be good to check there first :)

**Comment by THEb0nny** [comment]
@jwunderl no option to enable crowdin context translation editor?
image

**Comment by THEb0nny** [comment]
@jwunderl and also, I have a question, will you be able to build an offline version of the beta version of the application to use it in robotics competitions?

**Comment by jwunderl** [comment]
I pushed up https://github.com/microsoft/pxt/pull/9484 which *should* fix in context translations, just have to wait for build and I'll bump again over here and include it in a /v1.4.30 to test. 

Due to mindstorms & ev3 hardware / software support both ending end of last year, we won't be able to invest in building an offline app; best I can suggest is that we do have a service worker running (and prior to the appcache) so when I bump beta to include /v1.4.30 you should be able to continue to use /beta on any device that has previously used it, even when the device is offline.

**Comment by THEb0nny** [comment]
@jwunderl thanks for re-enabling crowdin.

**Comment by THEb0nny** [comment]
@jwunderl can you tell me how to change this background color? I don't understand where semantic.css comes from. Here it was necessary to restore the color of the button so that the text was correctly visible.
image

**Comment by jwunderl** [comment]
semantic.css gets build from the `theme` folder's .less files - you can add in an override in there just like a normal css file. It' probably needs defining a less variable defined, you can check if one of the changes in the pxt needs to be overridden in pxt-ev3/theme https://github.com/microsoft/pxt/commits/stable7.2

**Comment by THEb0nny** [comment]
@jwunderl I tested on ev3 robot. Motors, sensors, sounds, etc. everything works like a beta version.

**Pull request merged**
