### PR TITLE
Releasing offline app version 1.1.20

### PR DESCRIPTION
**Pull request by abchatra**

### CODE REVIEW

**Comment by pelikhan** [comment]
Yes!

**Comment by abchatra** [comment]
Links to try 
https://makecode.com/api/release/ev3/v1.1.20/win64
https://makecode.com/api/release/ev3/v1.1.20/mac64

**Comment by jwunderl** [comment]
mac version worked for me

**Comment by pelikhan** [comment]
Windows, HW OK

**Pull request merged**
