### PR TITLE
Bump pxt v9

### PR DESCRIPTION
**Pull request by THEb0nny**
Installed the latest version of pxt-core, pxt-common-common-packages.

Fieldeditors reworked to avoid build issues. Add search to pxtarget(workspaceSearch).

Take the added file \docs\static\loader.svg from microbit so that there are no problems during assembly. Will need to be redone. But I don't quite understand where it is used.

Removed the fix of the scrolling elements of the simulator, because. it is no longer required.

Fixed the background color of the toolbar on the add extension screen.

Added a picture of the Microsoft brand logo that is displayed on first launch. A bug was fixed where the brand logo and the project logo overlapped each other due to custom styles that were written for the ev3 project logo.

I'm seeing performance issues on my end after the big jump from pxt-core. I understand that these are problems on my part in wsl ubuntu. This makes it hard to work...

There is a problem that the automation extension has disappeared from the add extension window.

The high contrast feature works (didn't work before).

### CODE REVIEW

**Comment by THEb0nny** [comment]
@jwunderl please see the changes.

**Comment by THEb0nny** [comment]
The size of the loader.svg file turned out to be incorrect, it needs to be redone...

**Review by jwunderl — APPROVED** [review]

**Comment by THEb0nny** [comment]
image
image
Expanded the search field of the block to fit the width of the categories, it looks better.

**Comment by THEb0nny** [comment]
image

A different font was installed instead of fontawsome, and therefore the icons for the categories did not work.

**Comment by THEb0nny** [comment]
It turned out that it was icons that broke categories when adding storage, brodcast extensions.

image

**Comment by THEb0nny** [comment]
image
Icon sizes in these fonts turned out to be different. Native icons turned out to be smaller than fontawsome. I scaled them, and reduced the overall font size for the icons in the category.

**Comment by THEb0nny** [comment]
Due to the addition of the storage makecode extension, it starts to break.
The hex file is not available, please connect to internet and try again.

Looking at the console, I understood and found how this error is solved.
https://github.com/Microsoft/pxt-microbit/issues/1941
https://github.com/microsoft/pxt-common-packages/pull/782/files
https://github.com/tinkertanker/pxt-oled-ssd1306/pull/17

**Comment by THEb0nny** [comment]
I added the ability to change the separator for the CSV file, because I realized that, for example, MS Excel, depending on regional settings, could not be displayed correctly, so, in my region, a point with a comma (;) instead of a comma (,) is used in my region. The comma is used for separation in fractional numbers.

**Review by jwunderl — APPROVED** [review]

**Comment by THEb0nny** [comment]
@jwunderl thank you.

**Pull request merged**
