### PR TITLE
Updating npm dependencies and getting the build to work

### PR DESCRIPTION
**Pull request by riknoll**
The build *succeeds* but the blockly fields and sim are pretty broken.

I got rid of the motor field entirely since we brought that one into pxt.

### CODE REVIEW

**Comment by pelikhan** [comment]
Does it still work on hardware?

**Comment by riknoll** [comment]
@pelikhan I have done no testing on hardware

**Review by jwunderl — APPROVED** [review]

**Comment by THEb0nny** [comment]
@riknoll @pelikhan you need to take time to solve problems, I looked, but I do not understand anything to solve the problems that have arisen.

**Comment by THEb0nny** [comment]
@riknoll  why did you remove the motors field, if it served as a choice of motor ports? A + B, B + C and others?
And the one that you substituted this field for speed.
It was two whole fields. Choice of motor types: medium motor, large motor or two large motors and a field with ports.

**Comment by THEb0nny** [comment]
@riknoll after the changes there are a lot of errors that I myself don’t know how to fix even where to start... :(

**Comment by THEb0nny** [comment]
@pelikhan please help fix field_motors.ts in update. I can't manage to fix the problems that have arisen on my own.

**Pull request merged**
